Basic Numpy Operations

In [6]:
import numpy as np
# Addition => adds 2 arrays element wise

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = a + b
print(c)

# subtraction => subtracts 2 arrays element wise

c = b - a
print(c)

# Multiplication => multiplies 2 arrays element wise

c = b * a
print(c)

# Division => Divides 2 arrays element wise

c = b / a
print(c)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]


scalar operations => multiply or divide an array with an scalar value


In [7]:
#scalar operations

a = np.array([1,2,3,4,5])

b = a * 2
c = a / 2
print(b,c)

[ 2  4  6  8 10] [0.5 1.  1.5 2.  2.5]


np.sqrt() => return the square root of the elements in the array

In [ ]:
a = np.array([1,2,3,4,5])
print()

np.exp() ==> returns the exponential of each element in the array

In [8]:
a = np.array([1,2,3,4,5])

b = np.exp(a)

print(b)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Broadcasting
allows arithemtic operations between arrays of different shapes. Duplicates the smaller array along the missing dimesions to match the shapes of larger array without explicitly changing.`

In [11]:
# 1D Array and Scalar

a = np.array([1,2,3,4,5])
b = 2
c = a + b
print(c)

# 2D array and array

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = b + a
print(c)

[3 4 5 6 7]
[[2 4 6]
 [5 7 9]]


#### Rules to follow while broadcastitng
* If array have same shape, there is no need for broadcasting,the operation is conducted element wise
* If smaller size, Numpy attempts to broadcast the smaller arrays shape matching the size of the larger array
* if dimensions are different, then it starts from the left compares both the arrays and adds one to smaller one, trying make the dimesions both same.
* Once they hace same shape, it tries to match the size of each dimension, if one of the dimensions is one, it stretches to match the dimension of the other one