NumPy Arrays

In [2]:
import numpy as np

# shape return the dimensions of the array

# 1D arrays
array1 = np.array([1,2,3,4,5])
print(array1.shape)

# 2D arrays 
array2 = np.array ([[1,2,3],[4,5,6]])
print(array2.shape)

# 3D arrays
array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array3.shape)



(5,)
(2, 3)
(2, 2, 2)


In [3]:
import numpy as np

# size return the total number of elements in the array

a1 = np.array([1,2,3,4,5])
print(a1.size)


5


In [6]:
import numpy as np

# dtype return the data type of the elements in the array

a2 = np.array ([[1,2,3],[4,5,6]])
a3 = np.array ([[1.0,2.0,3.0],[4.0,5.0,6.0]])
a4 = np.array ([[1+2j,2+3j,3+4j],[4+5j,5+6j,6+7j]])
a5 = np.array ([[True,False,True],[False,True,False]])
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)

# also can specify the dtype when creating an array

a = np.array([1,2,3,4], dtype=np.float32)
print(a,a.dtype)

int64
float64
complex128
bool
[1. 2. 3. 4.] float32


np.array([]) ==> Used to create an array from a python list


np.asarray() ==> Convert input into array

In [9]:
import numpy as np

# from list

c = [1,2,3,4,5]
a1 = np.asarray(c)
print(a)

# from tuple

c1 = (10,20,40)
a1 = np.asarray(c1)
print(a1)


[1 2 3 4 5]
[10 20 40]


np.ones() ===> creates an array filled with ones

In [12]:
# creating a 1D array filled with ones

a = np.ones(5)
print(a)

# creating a 2D array filled with ones

a = np.ones((3,4))
print(a)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.zeros() ==> creates an array filled with zeros

In [14]:
# 1D array filled with zeros

b = np.zeros(4)
print(b)

#2D array filled with zeros

b = np.zeros((3,4))
print(b)


[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.empty() ==> creates an uninitialized array

In [19]:

# unintialized array 1D

b = np.empty(5)
print(b)

# 2D uninitialized array

b = np.empty((3, 4))
print(b)

[1. 1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.arange() ==> creates a sequence of numbers within a range

In [22]:
a = np.arange(20)
print(a)

# sequence from 3 to 10 with step 2

a = np.arange(3,10,2)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[3 5 7 9]


np.linspace() ==> array with evenly spaced values within a range

In [23]:
# 5 evenly spaced values between 0 and 1

a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


np.eye() ==> square identity matrix

In [25]:
# 2x2 identity matrix

a = np.eye(2)

print(a)

# 3x3 identity matrix

a = np.eye(3)
print(a)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
