Basic Numpy Operations

In [6]:
import numpy as np
# Addition => adds 2 arrays element wise

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = a + b
print(c)

# subtraction => subtracts 2 arrays element wise

c = b - a
print(c)

# Multiplication => multiplies 2 arrays element wise

c = b * a
print(c)

# Division => Divides 2 arrays element wise

c = b / a
print(c)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]


scalar operations => multiply or divide an array with an scalar value


In [7]:
#scalar operations

a = np.array([1,2,3,4,5])

b = a * 2
c = a / 2
print(b,c)

[ 2  4  6  8 10] [0.5 1.  1.5 2.  2.5]


np.sqrt() => return the square root of the elements in the array

In [ ]:
a = np.array([1,2,3,4,5])
print()

np.exp() ==> returns the exponential of each element in the array

In [8]:
a = np.array([1,2,3,4,5])

b = np.exp(a)

print(b)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Broadcasting
allows arithemtic operations between arrays of different shapes. Duplicates the smaller array along the missing dimesions to match the shapes of larger array without explicitly changing.`

In [11]:
# 1D Array and Scalar

a = np.array([1,2,3,4,5])
b = 2
c = a + b
print(c)

# 2D array and array

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = b + a
print(c)

[3 4 5 6 7]
[[2 4 6]
 [5 7 9]]


#### Rules to follow while broadcastitng
* If array have same shape, there is no need for broadcasting,the operation is conducted element wise
* If smaller size, Numpy attempts to broadcast the smaller arrays shape matching the size of the larger array
* if dimensions are different, then it starts from the left compares both the arrays and adds one to smaller one, trying make the dimesions both same.
* Once they hace same shape, it tries to match the size of each dimension, if one of the dimensions is one, it stretches to match the dimension of the other one

* if still doesnt match the prepending 1's afer broadcasting, it raises valueError

## Element - wise operations and their efficiency

* high efficiency manner
* operations are vectorized, maens they are applied to the entire arrays at once. Vectorizaion key factor to its efficiency avoiding the Python lvl loops and allows operations to perform at single step

In [2]:

import time
import numpy as np

# Create large arrays
a = np.random.rand(10000000)
b = np.random.rand(10000000)

# Element-wise operations in NumPy
start = time.time()
c = a + b
end = time.time()
print(f"NumPy element-wise addition took: {end - start:.6f} seconds")

# Element-wise operations in Python lists
start = time.time()
x = [i for i in range(10000000)]
y = [i for i in range(10000000)]
z = [x[i] + y[i] for i in range(10000000)]
end = time.time()
print(f"Python list element-wise addition took: {end - start:.6f} seconds")

NumPy element-wise addition took: 0.018996 seconds
Python list element-wise addition took: 1.879334 seconds


Above shows the efficiency of the numpy operations compared to the python level operations.

### Indexing and Slicing.

1. Basic Indexing


In [6]:
#1D array
a = np.array([1,2,3,4,5,6])
print(a[0])
print(a[5])

b = np.array([[1,2,3],[4,5,6]])
print(b[0,0])
print(b[1,0])

1
6
1
4


2. Fancy Indexing

In [12]:
#1D array
a = np.array([1,2,3,4,5,6])
indices = np.array([0,2,4])
print(a[indices])

#2D array
a = np.array([[1,2,3],[4,5,6]])
row = np.array([0,1])
cols = np.array([0,2])
print(b[row,cols])

[1 3 5]
[1 6]
